# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        target-framework: ['net8.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build ${{ matrix.target-framework }}
      run: dotnet build --configuration Release --framework ${{ matrix.target-framework }}

    - name: Test ${{ matrix.target-framework }}
      run: dotnet test --configuration Release --framework ${{ matrix.target-framework }} --no-restore --verbosity normal

    - name: Pack ${{ matrix.target-framework }}
      run: dotnet pack ./Src/NanoRabbit/NanoRabbit/NanoRabbit.csproj --configuration Release --framework ${{ matrix.target-framework }} --output ./nupkg/

    - name: Upload NuGet package
      uses: actions/upload-artifact@v3
      with:
        name: nupkg-${{ matrix.os }}-${{ matrix.target-framework }}
        path: ./nupkg/
